First useful compile script

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,3 +1,22 @@
-mvn clean
-g2v -c config.yml "$@"
-mvn install
+#!/bin/bash
+#set -x
+scrdir=`dirname $0`
+
+silentmvn="-q -ntp"
+
+echo "First run may take a while, be patient ... "
+status=0
+echo -n "Preparing, "
+mvn $silentmvn dependency:get -Dartifact=de.dfki.mlt:grave2vonda-compiler:1.1
+mvn $silentmvn clean
+
+echo -n "Compiling, "
+"$scrdir"/g2v -c config.yml "$@" || status=1
+mvn $silentmvn install
+
+if [ $status = 1 ]; then
+    echo "VOnDA/GraVE compilation failed!"
+else
+    echo "Success!"
+fi
+exit $status
